language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-6.1

matrix:
  include:
  - smalltalk: Pharo-6.1
    smalltalk_config: .smalltalk.ston
  - smalltalk: Pharo-6.1
    smalltalk_config: .smalltalk-debugging.ston