filein/out
definition
	^ { 
		{'entity.name'} . {  } .
		{'entity.other.inherited-class'} . {  } .
		{'entity.name.section'} . {  }  .
		{'entity.name.tag'} . {  } .
		{'entity.other.attribute-name'} . {  } . 
		{'variable'} . {  } .
		{'variable.language'} . {  } .
		{'variable.parameter'} . {  } .
		{'variable.function'} . {  } .
		{'constant'} . {  } .
		{'constant.numeric'} . {  } .
		{'constant.language'} . {  } .
		{'constant.character.escape'} . {  } . 
		{'storage.type'} . {  } . 
		{'storage.modifier'} . {  } . 
		{'support'} . {  } .
		{'keyword'} . {  } .
		{'keyword.control'} . {  } .
		{'keyword.operator'} . {  } .
		{'string'} . {  } .
		{'comment'} . {  } .
		{'invalid'} . {  } .
		{'invalid.deprecated'} . {  }
	}